using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Compilador.analizador_lexico
{
    class Estados //Todos los "estados" del automata
    {
        public static String RESERVADA_DESCRIPTION = "Palabra reservada \n";
        public static String IF_TOKEN = "if";
        public static String THEN_TOKEN = "then";
        public static String ELSE_TOKEN = "else";
        public static String DO_TOKEN = "do";     
        public static String WHILE_TOKEN = "while";
        public static String END_TOKEN = "end";
        public static String MAIN_TOKEN = "main";
        public static String CIN_TOKEN = "cin";
        public static String COUT_TOKEN = "cout";
        public static String FLOAT_TOKEN = "float";
        public static String REAL_TOKEN = "real";
        public static String INT_TOKEN = "int";
        public static String BOOLEAN_TOKEN = "boolean";
        public static String ID_TOKEN = "";
        public static String ID_DESCRIPTION = "Identificador\n";
        public static String NUM_INT_CSIGNO_TOKEN = "";
        public static String NUM_INT_CSIGNO_DESCRIPTION = "Numero entero con signo\n";
        public static String NUM_INT_SSIGNO_TOKEN = "";
        public static String NUM_INT_SSIGNO_DESCRIPTION = "Numero entero Sin signo\n";
        public static String NUM_FLOAT_SSIGNO_TOKEN = "";
        public static String NUM_FLOAT_SSIGNO_DESCRIPTION = "Numero flotante sin signo\n";
        public static String NUM_FLOAT_CSIGNO_DESCRIPTION = "Numero flotante con signo\n";
        public static String ASIGNACION_TOKEN = ":=";
        public static String ASIGNACION_DESCRIPTION = "Asignacion\n";
        public static String IGUALDAD_TOKEN = "==";
        public static String IGUALDAD_DESCRIPTION = "Igualdad\n";
        public static String MAYOR_QUE_TOKEN = ">";
        public static String MAYOR_QUE_DESCRIPTION = "Mayor que\n";
        public static String MENOR_QUE_TOKEN = "<";
        public static String MENOR_QUE_DESCRIPTION = "Menor que\n";
        public static String DIFERENTE_TOKEN = "!=";
        public static String DIFERENTE_DESCRIPTION = "Diferente\n";
        public static String MAYOR_IGUAL_TOKEN = ">=";
        public static String MAYOR_IGUAL_DESCRIPTION = "Mayor o igual\n";
        public static String MENOR_IGUAL_TOKEN = "<=";
        public static String MENOR_IGUAL_DESCRIPTION = "Menor o igual\n";
        public static String MAS_TOKEN = "+";
        public static String MAS_DESCRIPTION = "Signo mas\n";
        public static String MENOS_TOKEN = "-";
        public static String MENOS_DESCRIPTION = "Signo menos\n";
        public static String MULTI_TOKEN = "*";
        public static String MULTI_DESCRIPTION = "Signo multiplicacion\n";
        public static String MODULO_TOKEN = "%";
        public static String MODULO_DESCRIPTION = "Modulo\n";
        public static String INCREMENTO_TOKEN = "++";
        public static String INCREMENTO_DESCRIPTION = "Incremento\n";
        public static String DECREMENTO_TOKEN = "--";
        public static String DECREMENTO_DESCRIPTION = "Decremento\n";
        public static String DIVISION_TOKEN = "/";
        public static String DIVISION_DESCRIPTION = "Division\n";
        public static String PARENTESIS_ABRE_TOKEN = "(";
        public static String PARENTESIS_ABRE_DESCRIPTION = "Parentesis que abre\n";
        public static String PARENTESIS_CIERRA_TOKEN = ")";
        public static String PARENTESIS_CIERRA_DESCRIPTION = "Parentesis de cierre\n";
        public static String LLAVE_ABRE_TOKEN = "{";
        public static String LLAVE_ABRE_DESCRIPTION = "Llave que abre\n";
        public static String LLAVE_CIERRA_TOKEN = "}";
        public static String LLAVE_CIERRA_DESCRIPTION = "Llave de cierre\n";
        public static String COMA_TOKEN = ",";
        public static String COMA_DESCRIPTION = "Coma\n";
        public static String PUNTO_COMA_TOKEN = ";";
        public static String PUNTO_COMA_DESCRIPTION = "Punto y coma\n";
        public static String COMENTARIO_SIMPLE_TOKEN = "//";
        public static String COMENTARIO_SIMPLE_DESCRIPTION = "Comentario de una linea\n";
        public static String COMENTARIO_MULTIPLE_TOKEN = "/*";
        public static String COMENTARIO_MULTIPLE_DESCRIPTION = "Comentario Multiple \n";
        public static String ERROR_DESCRIPTION = "Error";
    }
}
